import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const textStyles = StyleSheet.create({
  TEXT_STYLE: {
    fontFamily: 'OfficinaSansExtraBoldC',
    fontSize: 15,
    fontWeight: '800',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.LIGHT_OLIVE_GREEN,
  },
  TEXT_STYLE_2: {
    fontFamily: 'OfficinaSansExtraBoldC',
    fontSize: 21,
    fontWeight: '800',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.WHITE,
  },
  TEXT_STYLE_3: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.BLACK_70,
  },
  TEXT_STYLE_4: {
    fontFamily: 'Roboto-Regular',
    fontSize: 11,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
  },
  TEXT_STYLE_5: {
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.BLACK_87,
  },
  TEXT_STYLE_6: {
    fontFamily: 'OfficinaSansExtraBoldC',
    fontSize: 21,
    fontWeight: '800',
    fontStyle: 'normal',
    lineHeight: 23,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.BLUE_GREY,
  },
  TEXT_STYLE_7: {
    fontFamily: 'Roboto-Medium',
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0.5,
    textAlign: 'center',
    color: colors.WHITE,
  },
  TEXT_STYLE_8: {
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'left',
    color: colors.BLACK_87,
  },
  TEXT_STYLE_9: {
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
    color: colors.WHITE,
  },
  TEXT_STYLE_10: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.BLACK_70,
  },
  TEXT_STYLE_NKO_TITLE: {
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.BLACK_60,
  },
  TEXT_STYLE_LINK: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.LEAF,
    textDecorationLine: 'underline',
  },
  TEXT_STYLE_HELP_BUTTON: {
    fontFamily: 'Roboto',
    fontSize: 10,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.BLACK_40,
  },
  TEXT_STYLE_DETAILS_TITLE: {
    fontFamily: 'OfficinaSansExtraBoldC',
    fontSize: 21,
    fontWeight: '800',
    fontStyle: 'normal',
    lineHeight: 23,
    letterSpacing: 0,
    color: colors.BLUE_GREY,
  },
  TEXT_STYLE_HELPERS_COUNT: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.BLACK_54,
  },
  TEXT_STYLE_SEARCH_TEXT: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'left',
    color: colors.BLACK_87,
  },
});
